version: '2'
services:
    portal-app:
        image: portal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://portal-postgresql:5432/portal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    portal-postgresql:
        extends:
            file: postgresql.yml
            service: portal-postgresql
